version: "3.6"

services:
  app:
    build:
      context: .
    container_name: 'app'
    ports:
      - 5000:5000
    volumes:
      - ./:/app
    env_file: 
      - .env
    environment:
      FLASK_ENV: development

  db:
    image: mysql
    container_name: 'db'
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=p@ssw0rd1
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql

    
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
  
  

volumes:
  mysql:
  mysql_config:
